version: "2.4"

services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile.dev
    volumes:
      # Host source code directory
      - ../:/app/
      # The line below is useful if using dbt interactively; should not be
      # needed for automated tests.
      #- ../tests/sqlfluff_templater/fixtures/dbt/profiles_yml:/root/.dbt
    depends_on:
      - postgres
    entrypoint: /bin/bash
    environment:
      - POSTGRES_HOST=postgres
    tty: true
    ports:
      - 8581:8581
  postgres:
    image: postgres:14-bullseye
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      # NOTE: "5432:5432" makes the Postgres server accessible to both the host
      # developer machine *and* the "app" container in Docker. If you don't want
      # it available on the host machine, change this to simply "5432".
      - 5432:5432
