FROM python:3.10-slim-bullseye

# Reason for this line: https://github.com/debuerreotype/docker-debian-artifacts/issues/24
RUN mkdir -p /usr/share/man/man1

# Install required binaries and remove installers/lists
RUN apt-get update && \
    apt-get install -y --no-install-recommends curl vim && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Set separate working directory for easier debugging.
WORKDIR /app

RUN pip install 'poetry==1.5.0'

# Copy everything. (Note: If needed, we can use .dockerignore to limit what's copied.)
COPY . .

RUN poetry install --extras postgres
